### ISSUE TITLE
Buying BTC

### ISSUE THREAD

**Issue by shea-brown** [wang-ye/robinhood-crypto#6]
I am trying to just experiment with the code, and im just trying to buy $1 worth of bitcoin and I have used the code from the examples with a few tweaks:

```
from robinhood_crypto_api import RobinhoodCrypto

r = RobinhoodCrypto('user', 'password')

quote_info = r.quotes()

usdAmount = 1

market_order_info = r.trade(
        'BTCUSD',
        price=round(float(quote_info['mark_price']) * 1.005, 2),
        quantity=str(usdAmount / float(quote_info['mark_price'])),
        side="buy",
        time_in_force="gtc",
        type="market"
    )

order_id = market_order_info['id']
print('market order {} status: {}'.format(order_id, r.order_status(order_id)))
```

but it's giving the beautiful error:

> P:\BTCTrader\venv\Scripts\python.exe C:/Users/Shea/.PyCharmCE2018.2/config/scratches/scratch.py
> 400 Client Error: Bad Request for url: https://nummus.robinhood.com/orders/
> Traceback (most recent call last):
>   File "P:\BTCTrader\robinhood-crypto-master\robinhood_crypto_api\robinhood_crypto_api.py", line 127, in session_request
>     resp.raise_for_status()
>   File "P:\BTCTrader\venv\lib\site-packages\requests\models.py", line 940, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://nummus.robinhood.com/orders/
> Traceback (most recent call last):
>   File "P:\BTCTrader\robinhood-crypto-master\robinhood_crypto_api\robinhood_crypto_api.py", line 234, in trade
>     res = self.session_request(RobinhoodCrypto.ENDPOINTS['orders'], json_payload=payload, method='post', timeout=5)
>   File "P:\BTCTrader\robinhood-crypto-master\robinhood_crypto_api\robinhood_crypto_api.py", line 50, in function_reauth
>     raise e
>   File "P:\BTCTrader\robinhood-crypto-master\robinhood_crypto_api\robinhood_crypto_api.py", line 40, in function_reauth
>     res = f(*args, **kwargs)
>   File "P:\BTCTrader\robinhood-crypto-master\robinhood_crypto_api\robinhood_crypto_api.py", line 131, in session_request
>     raise e
>   File "P:\BTCTrader\robinhood-crypto-master\robinhood_crypto_api\robinhood_crypto_api.py", line 127, in session_request
>     resp.raise_for_status()
>   File "P:\BTCTrader\venv\lib\site-packages\requests\models.py", line 940, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://nummus.robinhood.com/orders/
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:/Users/Shea/.PyCharmCE2018.2/config/scratches/scratch.py", line 15, in <module>
>     type="market"
>   File "P:\BTCTrader\robinhood-crypto-master\robinhood_crypto_api\robinhood_crypto_api.py", line 236, in trade
>     raise TradeException()
> robinhood_crypto_api.robinhood_crypto_api.TradeException
> 
> Process finished with exit code 1

I don't think it's a problem on my end? I definitely have access to buy and sell on my account so it's not that. Any help is greatly appreciated, thanks!

**Comment by shea-brown** [comment]
Found the issue, was with
`quantity=str(usdAmount / float(quote_info['mark_price']))`

Sorry about that, thanks anyways!
Closing now

**Comment by wang-ye** [comment]
good to know. have fun coding
